"""User Model

Revision ID: 52f512815582
Revises: 80fc41db9f30
Create Date: 2023-09-13 18:39:32.325092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f512815582'
down_revision: Union[str, None] = '80fc41db9f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trainings', sa.Column('training_owner', sa.String(), nullable=True))
    op.add_column('Trainings', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'Trainings', 'Users', ['owner_id'], ['id'])
    op.drop_column('Trainings', 'training_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trainings', sa.Column('training_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Trainings', type_='foreignkey')
    op.drop_column('Trainings', 'owner_id')
    op.drop_column('Trainings', 'training_owner')
    # ### end Alembic commands ###
