from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '577da013fe0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_name', sa.String(), nullable=True),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_appear', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Trainings',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('training_day', sa.String(), nullable=True),
                    sa.Column('training_time', sa.String(), nullable=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=True),
                    sa.Column('booked', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trainings')
    op.drop_table('Users')
    # ### end Alembic commands ###
