"""User Model

Revision ID: eea132d7d7ea
Revises: 52f512815582
Create Date: 2023-09-21 11:25:49.005831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea132d7d7ea'
down_revision: Union[str, None] = '52f512815582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trainings', sa.Column('booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Trainings', 'booked')
    # ### end Alembic commands ###
